spring.application.name=task_12
# Database Configuration for Standalone MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=indrani24820
spring.jpa.hibernate.ddl-auto=update

# This helps you see the SQL commands in the console (very helpful for class!)
spring.jpa.show-sql=true
